#!/usr/bin/env bash
set -euo pipefail

# Build a cPanel/Passenger-ready standalone deployment archive for Yegara.

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="$PROJECT_ROOT/yegara_dist"
ZIP_PATH="$PROJECT_ROOT/yegara-deploy.zip"

cd "$PROJECT_ROOT"

echo "[1/10] Pre-flight checks"
if ! command -v npm >/dev/null 2>&1; then
  echo "Error: npm is required but was not found in PATH."
  exit 1
fi

if ! command -v zip >/dev/null 2>&1; then
  echo "Error: zip is required but was not found in PATH."
  exit 1
fi

if ! command -v unzip >/dev/null 2>&1; then
  echo "Error: unzip is required but was not found in PATH."
  exit 1
fi

NEXT_CONFIG=""
if [[ -f "$PROJECT_ROOT/next.config.ts" ]]; then
  NEXT_CONFIG="$PROJECT_ROOT/next.config.ts"
elif [[ -f "$PROJECT_ROOT/next.config.mjs" ]]; then
  NEXT_CONFIG="$PROJECT_ROOT/next.config.mjs"
else
  echo "Error: Neither next.config.ts nor next.config.mjs was found."
  exit 1
fi

echo "Using Next.js config: ${NEXT_CONFIG#$PROJECT_ROOT/}"

if grep -Eq 'output\s*:\s*["\x27]standalone["\x27]' "$NEXT_CONFIG"; then
  echo "Standalone output already configured."
else
  echo "Adding output: 'standalone' to ${NEXT_CONFIG#$PROJECT_ROOT/}"
  # Insert output into a standard nextConfig object literal.
  if grep -Eq 'const\s+nextConfig[^=]*=\s*\{' "$NEXT_CONFIG"; then
    sed -i -E '/const\s+nextConfig[^=]*=\s*\{/a\  output: "standalone",' "$NEXT_CONFIG"
  else
    echo "Error: Could not automatically add output: 'standalone'."
    echo "Please define a nextConfig object, then run this script again."
    exit 1
  fi
fi

echo "[2/10] Verifying required runtime dependencies"
for dep in decimal.js date-fns bcryptjs; do
  if ! npm ls "$dep" >/dev/null 2>&1; then
    echo "Error: required dependency '$dep' is missing."
    echo "Install with: npm install $dep"
    exit 1
  fi
done

echo "[3/10] Generating Prisma client"
if ! npx prisma generate; then
  echo "Error: Prisma client generation failed."
  exit 1
fi

echo "[4/10] Running production build"
if ! npm run build; then
  echo "Error: Build failed. Aborting package creation."
  exit 1
fi

echo "[5/10] Reconstructing standalone package directory"
if [[ ! -d "$PROJECT_ROOT/.next/standalone" ]]; then
  echo "Error: .next/standalone was not generated."
  echo "Verify Next.js standalone output and try again."
  exit 1
fi

if [[ ! -d "$PROJECT_ROOT/.next/static" ]]; then
  echo "Error: .next/static was not generated by the build."
  exit 1
fi

rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR"

# The core standalone payload (server.js + traced node_modules).
cp -a "$PROJECT_ROOT/.next/standalone/." "$DIST_DIR/"

# Hidden brain: explicitly copy .next from standalone to ensure inclusion.
if [[ -d "$PROJECT_ROOT/.next/standalone/.next" ]]; then
  cp -a "$PROJECT_ROOT/.next/standalone/.next" "$DIST_DIR/.next"
else
  mkdir -p "$DIST_DIR/.next"
fi

# Static assets required at runtime for CSS/JS.
mkdir -p "$DIST_DIR/.next"
cp -a "$PROJECT_ROOT/.next/static" "$DIST_DIR/.next/static"

if [[ -d "$PROJECT_ROOT/public" ]]; then
  cp -a "$PROJECT_ROOT/public" "$DIST_DIR/public"
else
  echo "Warning: public directory not found; creating empty yegara_dist/public"
  mkdir -p "$DIST_DIR/public"
fi

echo "[6/10] Copying Prisma schema/runtime files"
if [[ ! -d "$PROJECT_ROOT/prisma" ]]; then
  echo "Error: prisma directory is missing."
  exit 1
fi
cp -a "$PROJECT_ROOT/prisma" "$DIST_DIR/prisma"

echo "[7/10] Verifying entry point"
if [[ ! -f "$DIST_DIR/server.js" ]]; then
  echo "Error: server.js is missing in yegara_dist root."
  echo "The cPanel Node.js app needs this startup file."
  exit 1
fi

echo "[8/10] Creating deployment zip"
rm -f "$ZIP_PATH"
(
  cd "$DIST_DIR"
  zip -r ../yegara-deploy.zip . -i "*" >/dev/null
)

echo "[9/10] Verifying deployment zip contents"
ZIP_LISTING="$(unzip -l "$ZIP_PATH")"

echo "$ZIP_LISTING" | grep -Eq '(^|[[:space:]])server\.js$' || {
  echo "Error: server.js was not found in yegara-deploy.zip"
  exit 1
}

echo "$ZIP_LISTING" | grep -Eq '[[:space:]]\.next/$|[[:space:]]\.next/' || {
  echo "Error: .next/ was not found in yegara-deploy.zip"
  exit 1
}

echo "Verified: yegara-deploy.zip contains server.js and .next/"

echo "[10/10] Cleaning temporary directory"
rm -rf "$DIST_DIR"

echo ""
echo "Success: Standalone deployment archive created"
echo "ZIP: $ZIP_PATH"
